using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Diagnostics;
using Xceed.Document.NET;
using Xceed.Words.NET;
using System.IO;

namespace lab_12_big_button
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
            displayText.Text = "This took: 0ms";
        }

        private void GoButton_Click(object sender, RoutedEventArgs e)
        {
            var stopwatch = new Stopwatch();
            stopwatch.Start();

            string folderName = @"C:\2020-06-labs\2020-06-c-sharp-labs\labs\lab_12_big_button";
            string pathString = System.IO.Path.Combine(folderName, "textFolder");
            System.IO.Directory.CreateDirectory(pathString);

            for (int i = 0; i <= 100; i++)
            {
                string pathFile = $@"C:\2020-06-labs\2020-06-c-sharp-labs\labs\lab_12_big_button\textFolder\textfile{i}.txt";

                using (StreamWriter sw = File.CreateText(pathFile));

                for (int n = 0; n < 10; n++)
                {
                    string line = $"The value of i is {n} at {DateTime.Now} \n";
                    File.AppendAllText(pathFile, line);
                }
            }

            var document = DocX.Create("MyReport.docx");
            document.InsertParagraph("This is an amazing report");
            document.InsertParagraph($"Report generated by <<author>> {DateTime.Now}");
            document.Save();
            Process.Start("WINWORD.EXE", "MyReport.docx");

            stopwatch.Stop();
            displayText.Text = $"This took: {stopwatch.ElapsedMilliseconds}ms";
        }
    }
}
